 # Exercises XP

##  Exercise 1 : Array Creation And Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

In [2]:
import pandas as pd
import numpy as np

In [3]:
array1 = np.arange(10)

array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##  Exercise 2 : Type Conversion And Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [4]:
list1 = [3.14, 2.17, 0, 1, 2]

array2 = np.array(list1)
array_int = array2.astype(int)

array_int

array([3, 2, 0, 1, 2])

##  Exercise 3 : Working With Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

In [5]:
array3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##  Exercise 4 : Creating Multi-Dimensional Array With Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [7]:
array4 = np.random.rand(4, 5).round(2)

array4

array([[0.73, 0.35, 0.39, 0.26, 0.56],
       [0.9 , 0.77, 0.38, 0.16, 0.51],
       [0.08, 0.49, 0.62, 0.95, 0.55],
       [0.23, 0.84, 0.31, 0.35, 0.52]])

##  Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

In [8]:
array5 = np.array([[0, 1, 2, 3, 4],
                        [20, 21, 22, 23, 24],
                        [40, 41, 42, 43, 44]])

second_row = array5[1]
second_row

array([20, 21, 22, 23, 24])

## Exercise 6 : Reversing Elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [10]:
array6 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

reversed_array = np.flip(array6)
reversed_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

##  Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

In [11]:
identity_matrix = np.eye(4)

identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

In [12]:
array8 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

sum_value = np.sum(array8)
average_value = np.mean(array8)

print(f"Sum: {sum_value}, Average: {average_value}")

Sum: 55, Average: 5.5


##  Exercise 9 : Create Array And Change Its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [13]:
array9 = np.arange(1, 21)

reshaped_array = array9.reshape(4, 5)
reshaped_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

##  Exercise 10 : Conditional Selection Of Values
Instructions
Extract all odd numbers from a given NumPy array.

In [14]:
array10 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

odd_numbers = array10[array10 % 2 != 0]
odd_numbers

array([1, 3, 5, 7, 9])